name: Update latest blog posts

on:
  schedule:
    - cron: "0 12 * * 1,4"
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: ${{ secrets.BLOG_FEED_URL }}
          max_post_count: 5
          date_format: "yyyy-MM-dd"
          template: |
            | [$title]($url) | $date |
          remove_duplicates: true

